[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "grasplan"
authors = [{name = "Oscar Lima", email = "oscar.lima@dfki.de"}]
dynamic = ["version", "description"]
